name: jax_huggingface
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - astroid=3.0.1=py310hff52083_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotli=1.0.9=h166bdaf_9
  - brotli-bin=1.0.9=h166bdaf_9
  - brotli-python=1.0.9=py310hd8f1fbe_9
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.11.17=hbcca054_0
  - certifi=2023.11.17=pyhd8ed1ab_0
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.1.0=py310hd41b1e2_0
  - cpuonly=2.0=0
  - cuda-nvcc=12.2.140=0
  - cuda-version=11.8=h70ddcb2_2
  - cudatoolkit=11.8.0=h4ba93d1_12
  - cudnn=8.8.0.121=h838ba91_2
  - cycler=0.11.0=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - dill=0.3.7=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.12.4=pyhd8ed1ab_0
  - fonttools=4.42.1=py310h2372a71_0
  - freetype=2.12.1=hca18f0e_1
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py310h3ec546c_1
  - gnutls=3.6.13=h85f3911_1
  - icu=73.2=h59595ed_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - ipython=8.15.0=pyh0d859eb_0
  - isort=5.12.0=pyhd8ed1ab_1
  - jax=0.4.12=pyhd8ed1ab_0
  - jaxlib=0.4.12=cuda112py310h7b441b9_201
  - jedi=0.19.0=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - kiwisolver=1.4.5=py310hd41b1e2_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230125.3=cxx17_h59595ed_0
  - libblas=3.9.0=16_linux64_mkl
  - libbrotlicommon=1.0.9=h166bdaf_9
  - libbrotlidec=1.0.9=h166bdaf_9
  - libbrotlienc=1.0.9=h166bdaf_9
  - libcblas=3.9.0=16_linux64_mkl
  - libdeflate=1.17=h0b41bf4_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.1.0=he5830b7_0
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libgomp=13.1.0=he5830b7_0
  - libgrpc=1.56.2=h3905398_1
  - libhwloc=2.9.2=default_h554bfaf_1009
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=16_linux64_mkl
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.23=pthreads_h80387f5_0
  - libpng=1.6.39=h753d276_0
  - libprotobuf=4.23.3=hd1fb520_0
  - libsqlite=3.43.0=h2797004_0
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.1=hd590300_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.11.5=h232c23b_1
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=16.0.6=h4dfa4b3_0
  - markupsafe=2.1.3=py310h2372a71_0
  - matplotlib-base=3.7.2=py310hf38f957_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mccabe=0.7.0=pyhd8ed1ab_0
  - mkl=2022.2.1=h84fe81f_16997
  - ml_dtypes=0.2.0=py310h7cbd5c2_1
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.0=hb012696_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nccl=2.18.5.1=h0800d71_0
  - ncurses=6.4=hcb278e6_0
  - nettle=3.6=he412f7d_0
  - networkx=3.1=pyhd8ed1ab_0
  - numpy=1.25.2=py310ha4c1d20_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.2.0=hd590300_1
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.0.3=py310h7cbd5c2_1
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py310h023d228_1
  - pip=23.2.1=pyhd8ed1ab_0
  - platformdirs=3.10.0=pyhd8ed1ab_0
  - pooch=1.7.0=pyha770c72_3
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pylint=3.0.2=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.0=h543edf9_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.10=3_cp310
  - pytorch=2.0.1=py3.10_cpu_0
  - pytorch-mutex=1.0=cpu
  - pytz=2023.3=pyhd8ed1ab_0
  - re2=2023.03.02=h8c504da_0
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - scikit-learn=1.3.0=py310hf7d194e_0
  - scipy=1.11.2=py310ha4c1d20_0
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - setuptools=68.1.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.43.0=h2c6b66d_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.0=py310h278f3c1_1
  - sympy=1.12=pypyh9d50eac_103
  - tbb=2021.10.0=h00ab1b0_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tk=8.6.12=h27826a3_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.12.3=pyha770c72_0
  - torchaudio=2.0.2=py310_cpu
  - torchvision=0.15.2=py310_cpu
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - tzdata=2023c=h71feb2d_0
  - unicodedata2=15.0.0=py310h5764c6d_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - absl-py==1.4.0
      - astunparse==1.6.3
      - cachetools==5.3.1
      - chex==0.1.82
      - dm-haiku==0.0.11.dev0
      - dm-tree==0.1.8
      - docopt==0.6.2
      - etils==1.4.1
      - flatbuffers==23.5.26
      - flax==0.7.2
      - gast==0.4.0
      - gitdb==4.0.10
      - gitpython==3.1.32
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.57.0
      - h5py==3.9.0
      - importlib-resources==6.0.1
      - jmp==0.0.4
      - jsonpickle==3.0.2
      - keras==2.13.1
      - libclang==16.0.6
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - msgpack==1.0.5
      - munch==2.5.0
      - nest-asyncio==1.5.7
      - oauthlib==3.2.2
      - optax==0.1.7
      - orbax-checkpoint==0.3.5
      - protobuf==4.24.2
      - py-cpuinfo==9.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyyaml==6.0.1
      - requests-oauthlib==1.3.1
      - rich==13.5.2
      - rsa==4.9
      - sacred==0.8.4
      - smmap==5.0.0
      - tabulate==0.9.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - tensorflow==2.13.0
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.33.0
      - tensorstore==0.1.41
      - termcolor==2.3.0
      - toolz==0.12.0
      - typing-extensions==4.5.0
      - urllib3==1.26.16
      - werkzeug==2.3.7
      - wrapt==1.15.0
prefix: /home/trungt1/mambaforge/envs/jax_huggingface
